import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import About from "./About";
import Contact from "./Contact";
import Gallery from "./Gallery";
import HomePage from "./HomePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Modern Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar/>
      <HomePage/>
      <About/>
      <Gallery/>
      <Contact/>
      <Footer/>
    </div>
  );
}
